### PR TITLE
Add Cloudflare Pages

### PR DESCRIPTION
**Pull request by Chinoman10**
# Pull Request Template

Please ensure all items below are checked before creating a pull request:

-   [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
-   [x] My submission is ordered alphabetically
-   [x] My submission has a useful description
-   [x] I have searched the repository for any relevant issues or pull requests
-   [x] All changes have been squashed into a single commit

### CODE REVIEW

**Comment by marcelscruz** [comment]
Thank you for contributing Sérgio.

Unfortunately, you added the resource on the auto-generated DB file.
Instead, it should be added on the file referent to its initial letter ([here](https://github.com/marcelscruz/dev-resources/blob/main/resources/c.js)), and then some scripts will look after adding it to the DB and README files.

I believe the [contribution](https://github.com/marcelscruz/dev-resources/blob/main/CONTRIBUTING.md) guide might help you understand it better.

**Comment by Chinoman10** [comment]
Dang it, thank you @marcelscruz , I'll correct it 😊
Not sure how I misread that bit 😬

**Comment by Chinoman10** [comment]
@marcelscruz sorry for the delay, I corrected the mistake 👍

**Comment by marcelscruz** [comment]
Thank you, @Chinoman10!

**Pull request merged**
