### PR TITLE
Add Hackertab.dev resource

### PR DESCRIPTION
**Pull request by medyo**
[Hackertab](https://hackertab.dev) is the perfect extension for developers looking to stay up-to-date on the latest news, tools, and events in the tech industry.  🚀

-   [x] My changes were made in the `resources` folder, not in the auto-generated `README.md` file or `db` folder
-   [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
-   [x] My submission is ordered alphabetically based on the resource `name`
-   [x] My submission has a useful description
-   [x] I have searched the repository for any relevant issues or pull requests

### CODE REVIEW

**Comment by marcelscruz** [comment]
Thank you1

**Comment by medyo** [comment]
Thank you @marcelscruz.

I think the screenshot is broken, can you take a look at.
If not possible, I can provide an alternative image
image

Thank you

**Comment by marcelscruz** [comment]
Hi @medyo.

The screenshot is taken with a script, and it didn't wait the loading to be finished.
I've manually fixed it, but it's now cached in Vercel's server, and even a new deploy didn't update it.
I believe we'll have to wait until it's purged, otherwise when I have a bit more time I'll look up how to fix it.

**Comment by medyo** [comment]
Alright, thank you @marcelscruz
and happy new year

**Comment by marcelscruz** [comment]
Thank you, happy new year to you too!

**Pull request merged**
