### PR TITLE
Add RemoteSalary RemoteSalary.ai

### PR DESCRIPTION
**Pull request by salarysearch**
20,000+ jobs all over $150,000 salary. Find your ideal high paying remote role. Searches 2,000,000+ job postings across 12,000+ companies daily to find the highest paying remote roles.

# Pull Request Template

Please ensure all items below are checked before creating a pull request:

-   [x] My changes were made in the `resources` folder, not in the auto-generated `README.md` file or `db` folder
-   [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
-   [x] My submission is ordered alphabetically based on the resource `name`
-   [x] My submission has a useful description
-   [x] I have searched the repository for any relevant issues or pull requests

### CODE REVIEW

**Comment by marcelscruz** [comment]
Hi @salarysearch, thank you for the contribution.
Could you please remove the UTM params on the URL?
Those URLs need to be clean, so whichever use of it can set them separately.

**Comment by salarysearch** [comment]
> Hi @salarysearch, thank you for the contribution. Could you please remove the UTM params on the URL? Those URLs need to be clean, so whichever use of it can set them separately.

Done

**Comment by marcelscruz** [comment]
Thank you1

**Comment by marcelscruz** [comment]
Thank you!

**Pull request merged**
