### PR TITLE
Added Schedles

### PR DESCRIPTION
**Pull request by eshut**
# Pull Request Template

Please ensure all items below are checked before creating a pull request:

-   [x] My changes were made in the `resources` folder, not in the auto-generated `README.md` file or `db` folder
-   [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
-   [x] My submission is ordered alphabetically based on the resource `name`
-   [x] My submission has a useful description
-   [x] I have searched the repository for any relevant issues or pull requests

### CODE REVIEW

**Comment by marcelscruz** [comment]
Thank you for the contribution, but it's not a tool specifically for developers.

**Comment by eshut** [comment]
@marcelscruz huh? Literally our competitor :D
image

**Comment by marcelscruz** [comment]
I understand @eshut, but we're being a bit more strict now with the resources being added, as the surge of directories has brought many not-so-dev-related products just trying to get a backlink, and ultimately killing the purpose of Dev Resources.

I hope you understand this decision.

**Comment by eshut** [comment]
@marcelscruz Yeah, I see. I'll get back to you as we start some new project/technology for devs in future then :)

**Pull request closed without merging**
