### PR TITLE
Update Tabler Icons website url

### PR DESCRIPTION
**Pull request by codecalm**
Hi! Thank you for great stuff, but link to official website is https://tabler-icons.io. Your site (tablericons.com) is not linked to our project and serve old version of icons - Tabler Icons now contains over 3000 icons :)

You can verify it here:
- https://github.com/tabler/tabler-icons
- https://twitter.com/codecalm

Have a nice day!
Paweł Kuna - creator of Tabler icons :)

# Pull Request Template

Please ensure all items below are checked before creating a pull request:

-   [x] My changes were made in the `resources` folder, not in the auto-generated `README.md` file or `db` folder
-   [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
-   [x] My submission is ordered alphabetically based on the resource `name`
-   [x] My submission has a useful description
-   [x] I have searched the repository for any relevant issues or pull requests

### CODE REVIEW

**Comment by marcelscruz** [comment]
Hi @codecalm, thank you for contributing!

I suggest adding your resource as a new one, without removing the existing one, as it can still be useful to some folks.
Feel free to add "(Official)" or something like this beside the name, if you prefer.

What do you think?

**Comment by codecalm** [comment]
@marcelscruz thank you for your reply. The problem is that the author of this site uses the name Tabler Icons and a lot of people think this is the site of our project. The author himself is misleading on the site and is distributing icons that he is not the author of. 

That site uses an old version of the icons and has not been updated for a long time and people write to us to make corrections and do an update, but that site is not linked to our project.

**Comment by marcelscruz** [comment]
Understood.

I'm merging your changes then, and I hope that helps your project. :)

**Comment by codecalm** [comment]
thank you! :)

**Pull request merged**
